stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: pdf-approval-manager
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}:${CI_COMMIT_SHORT_SHA}

  NODEPORT: 32724


containerization:
  stage: containerization
  tags:
    - moreillon
  only:
    - master
  script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building
    - docker build -t ${CONTAINER_IMAGE} .
    # Tagging
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    # Pushing
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}
    # cleanup
    - docker image rm ${CONTAINER_IMAGE}
    - docker image rm ${CONTAINER_IMAGE_TAGGED}


deployment:
  stage: deployment
  tags:
    - moreillon
  only:
    - master
  script:
    # create/update the deployment
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    # Pull latest image of deployment
    - kubectl rollout restart deployment/${APPLICATION_NAME}

  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # Obtained from GitLab
